export const EVENT_NAME = {
    contractUploadPhoto1: 'contractUploadPhoto1',
    refreshContract: 'refreshContract',
    activeContractSuccess: 'activeContractSuccess',
    viewCreatorPhotoOfFace: 'viewCreatorPhotoOfFace',
    selectStar: 'selectStar',
    beingActiveContract: 'beingActiveContract',
    reqClaimantSuccess: 'reqClaimantSuccess',
    refetchPlotData: 'refetchPlotData',
    gotoPendingClaimantReq: 'gotoPendingClaimantReq',
    gotoPendingClaimantReq2: 'gotoPendingClaimantReq2',
    alertChangeContractStatus: 'alertChangeContractStatus',
    removeClaimantSuccess: 'removeClaimantSuccess',
    refetchRemoveClaimantReq: 'refetchRemoveClaimantReq',
    submitOtp: 'submitOtp',
    goodAlert: 'goodAlert',
    goodAlert2: 'goodAlert2',
    refreshMap: 'refreshMap',
    refreshWithdrawReceipt: 'refreshWithdrawReceipt',
    refreshPlotList: 'refreshPlotList',
    openAttestModal: 'openAttestModal',
};
